import"./assets/styles-COSbD4d6.js";import{a as p,i as c}from"./assets/vendor-CJ_tX8LA.js";const P="https://dummyjson.com",m={CATEGORIES:"/products/category-list",PRODUCTS:"/products",BYECATEGORY:"products/category/",ID:"/"},E=12;p.defaults.baseURL=P;async function S(){const{data:t}=await p(`${m.CATEGORIES}`);return t}async function L(t){const o=(t-1)*12,{data:e}=await p(`${m.PRODUCTS}?limit=${E}&skip=${o}`);return e}async function v(t,o){const e=(o-1)*12,{data:s}=await p(`${m.BYECATEGORY}${t}?limit=${E}&skip=${e}`);return s}async function T(t){const{data:o}=await p(`${m.PRODUCTS}/${t}`);return o}function g(t,o="success"){const e={message:t,position:"topRight",timeout:5e3};switch(o){case"success":c.success(e);break;case"error":c.error(e);break;case"warning":c.warning(e);break;case"info":c.info(e);break;default:c.error({message:`Invalid type of toast: ${o}`,position:"topRight",timeout:5e3});break}}const a={categories:document.querySelector(".categories"),products:document.querySelector(".products"),loadMoreBtn:document.querySelector(".load-more-btn"),loader:document.querySelector(".loader"),notFound:document.querySelector(".not-found"),modalProduct:document.querySelector(".modal-product"),modal:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn")};function C(t){const o=t.map(e=>`<li class="categories__item">
   <button class="categories__btn" type="button" data-category="${e}">${e}</button>
 </li>`).join("");a.categories.innerHTML=o}function d(t){const o=t.map(({thumbnail:e,title:s,id:r,brand:_,category:y,price:h})=>`<li class="products__item" data-id="${r}">
    <img class="products__image" src="${e}" alt="${s}"/>
    <p class="products__title">${s}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${_}</span></p>
    <p class="products__category">Category: ${y}</p>
    <p class="products__price">Price: ${h}</p>
 </li>`).join("");a.products.insertAdjacentHTML("beforeend",o)}function l(){a.loadMoreBtn.classList.remove("is-hidden")}function b(){a.loadMoreBtn.classList.add("is-hidden")}function $(){a.loader.classList.remove("is-hidden")}function f(){a.loader.classList.add("is-hidden")}function u(){a.notFound.classList.add("not-found--visible")}function w(){a.notFound.classList.remove("not-found--visible")}function B(){a.products.innerHTML=""}function R({thumbnail:t,title:o,tags:e,description:s,shippingInformation:r,returnPolicy:_,price:y}){const h=`<img class="modal-product__img" src="${t}" alt="${o}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${o}</p>
        <ul class="modal-product__tags">${e}</ul>
        <p class="modal-product__description">${s}</p>
        <p class="modal-product__shipping-information">Shipping:${r}</p>
        <p class="modal-product__return-policy">Return Policy:${_}</p>
        <p class="modal-product__price">Price:${y} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;a.modalProduct.insertAdjacentHTML("beforeend",h)}function A(){a.modal.classList.add("modal--is-open")}function M(){a.modal.classList.remove("modal--is-open")}function q(t){(t.target.classList.contains("modal")||t.target.classList.contains("modal__close-btn"))&&(M(),document.removeEventListener("keydown",k),a.modalProduct.innerHTML="")}function k(t){t.key==="Escape"&&(M(),document.removeEventListener("keydown",k),a.modalProduct.innerHTML="")}let n=1,i="";async function O(){try{n=1,w(),b(),$();const o=["all",...await S()];C(o),document.querySelector(".categories__btn").classList.add("categories__btn--active");const{products:e,skip:s,total:r}=await L(n);if(e.length===0){u();return}d(e),r-(s+12)>0&&l()}catch{g("smth wrong,try again, pls","error")}finally{f()}}async function I(){n+=1;try{if(w(),b(),$(),i===""){const{products:t,skip:o,total:e}=await L(n);if(t.length===0){u();return}d(t),e-(o+12)>0&&l()}else{const{products:t,skip:o,total:e}=await v(i,n);if(t.length===0){u();return}d(t),e-(o+12)>0&&l()}}catch{g("smth wrong,try again, pls","error")}finally{f()}}async function H(t){if(t.target.nodeName==="BUTTON"){i=t.target.dataset.category,document.querySelectorAll(".categories__btn").forEach(o=>{o.classList.remove("categories__btn--active")}),t.target.classList.add("categories__btn--active");try{if(n=1,B(),w(),b(),$(),i==="all"){const{products:o,skip:e,total:s}=await L(n);if(o.length===0){u();return}d(o),s-(e+12)>0&&l()}else{const{products:o,skip:e,total:s}=await v(i,n);if(o.length===0){u();return}d(o),s-(e+12)>0&&l()}}catch{g("smth wrong,try again, pls","error")}finally{f()}}}async function D(t){const o=t.target.closest("li").dataset.id;try{const e=await T(o);R(e),A(),a.modal.addEventListener("click",q),document.addEventListener("keydown",k)}catch{g("smth wrong,try again, pls","error")}finally{f()}}document.addEventListener("DOMContentLoaded",O);a.loadMoreBtn.addEventListener("click",I);a.categories.addEventListener("click",H);a.products.addEventListener("click",D);
//# sourceMappingURL=index.js.map
