import"./assets/styles-COSbD4d6.js";import{a as c}from"./assets/vendor-N5iQpiFS.js";const $="https://dummyjson.com",i={CATEGORIES:"/products/category-list",PRODUCTS:"/products"},b=12;c.defaults.baseURL=$;async function w(){const{data:t}=await c(`${i.CATEGORIES}`);return t}async function d(t){const e=(t-1)*12,{data:o}=await c(`${i.PRODUCTS}?limit=${b}&skip=${e}`);return o}const s={categories:document.querySelector(".categories"),products:document.querySelector(".products"),loadMoreBtn:document.querySelector(".load-more-btn"),loader:document.querySelector(".loader"),notFound:document.querySelector(".not-found")};function P(t){const e=t.map(o=>`<li class="categories__item">
   <button class="categories__btn" type="button" data-category="${o}">${o}</button>
 </li>`).join("");s.categories.innerHTML=e}function u(t){const e=t.map(({thumbnail:o,title:n,id:r,brand:h,category:y,price:L})=>`<li class="products__item" data-id="${r}">
    <img class="products__image" src="${o}" alt="${n}"/>
    <p class="products__title">${n}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${h}</span></p>
    <p class="products__category">Category: ${y}</p>
    <p class="products__price">Price: ${L}</p>
 </li>`).join("");s.products.insertAdjacentHTML("beforeend",e)}function l(){s.loadMoreBtn.classList.remove("is-hidden")}function p(){s.loadMoreBtn.classList.add("is-hidden")}function m(){s.loader.classList.remove("is-hidden")}function f(){s.loader.classList.add("is-hidden")}function g(){s.notFound.classList.add("not-found--visible")}function _(){s.notFound.classList.remove("not-found--visible")}let a=1;async function S(){try{_(),p(),m();const e=["all",...await w()];P(e);const{products:o,skip:n,total:r}=await d(a);if(o.length===0){g();return}u(o),r-(n+12)>0&&l()}catch{showToast("smth wrong,try again, pls","error")}finally{f()}}async function E(){a+=1;try{_(),p(),m();const{products:t,skip:e,total:o}=await d(a);if(t.length===0){g();return}u(t),o-(e+12)>0&&l()}catch{showToast("smth wrong,try again, pls","error")}finally{f()}}document.addEventListener("DOMContentLoaded",S);s.loadMoreBtn.addEventListener("click",E);
//# sourceMappingURL=index.js.map
